idf_component_register(
    SRCS
        "main.cpp"
        "sensor.cpp"
        "radio.cpp"
        "logger.cpp"
        "server.cpp"
        "libraries/RadioHead/RH_RF69.cpp"
        "libraries/RadioHead/RHGenericDriver.cpp"
        "libraries/RadioHead/RHGenericSPI.cpp"
        "libraries/RadioHead/RHSPIDriver.cpp"
        "libraries/RadioHead/RHHardwareSPI.cpp"
        "libraries/Adafruit_BMP3XX_Library/Adafruit_BMP3XX.cpp"
        "libraries/Adafruit_BusIO/Adafruit_I2CDevice.cpp"
        "libraries/Adafruit_BusIO/Adafruit_SPIDevice.cpp"
        "libraries/Adafruit_BusIO/Adafruit_BusIO_Register.cpp"
        "libraries/Adafruit_Unified_Sensor/Adafruit_Sensor.cpp"
        "libraries/Adafruit_BMP3XX_Library/bmp3.c"
    INCLUDE_DIRS
        "."
        "libraries/RadioHead"
        "libraries/Adafruit_BMP3XX_Library"
        "libraries/Adafruit_BusIO"
        "libraries/Adafruit_Unified_Sensor"
    REQUIRES arduino
)